### ISSUE TITLE
-es.timeout is not defined

### ISSUE THREAD

**Issue by occelebi** [justwatchcom/elasticsearch_exporter#171]
Hi team

Thanks for exporter. When I give `-es.timeout 10s` as command arguments, it shows me not defined error.

```
    image: justwatch/elasticsearch_exporter:${ELASTICSEARCH_EXPORTER_TAG:-latest}
    command:
     - '-es.uri=http://elasticsearch:9200'
     - '-es.timeout 10s'
     - '-es.all'
     - '-es.indices'
    restart: always
```

elasticsearch_exporter    | flag provided but not defined: -es.timeout 20s
elasticsearch_exporter    | Usage of /bin/elasticsearch_exporter:
elasticsearch_exporter    |   -es.all
elasticsearch_exporter    |     	Export stats for all nodes in the cluster.
elasticsearch_exporter    |   -es.ca string
elasticsearch_exporter    |     	Path to PEM file that conains trusted CAs for the Elasticsearch connection.
elasticsearch_exporter    |   -es.client-cert string
elasticsearch_exporter    |     	Path to PEM file that conains the corresponding cert for the private key to connect to Elasticsearch.
elasticsearch_exporter    |   -es.client-private-key string
elasticsearch_exporter    |     	Path to PEM file that conains the private key for client auth when connecting to Elasticsearch.
elasticsearch_exporter    |   -es.indices
elasticsearch_exporter    |     	Export stats for indices in the cluster.
elasticsearch_exporter    |   -es.timeout duration
elasticsearch_exporter    |     	Timeout for trying to get stats from Elasticsearch. (default 5s)
elasticsearch_exporter    |   -es.uri string
elasticsearch_exporter    |     	HTTP API address of an Elasticsearch node. (default "http://localhost:9200")
elasticsearch_exporter    |   -version
elasticsearch_exporter    |     	Show version and exit
elasticsearch_exporter    |   -web.listen-address string
elasticsearch_exporter    |     	Address to listen on for web interface and telemetry. (default ":9108")
elasticsearch_exporter    |   -web.telemetry-path string
elasticsearch_exporter    |     	Path under which to expose metrics. (default "/metrics")
elasticsearch_exporter exited with code 2
