### ISSUE TITLE
Basic Authorization header?

### ISSUE THREAD

**Issue by dkmbw** [justwatchcom/elasticsearch_exporter#404]
Hello,
i have a elasticsearch which is secured by a basic authorization header. so https://user:password@ES_URL:port/ does not work, but user and pass are in basic auth transformed. Do you support this?

**Comment by djkormo** [comment]
Enviroment variable should be based on several envs.  

https://$(ES_USER):$(ES_PASSWORD)@$(ES_HOST):$(ES_PORT)

Password should by saved in kubernetes secret (here my-secret-elastic-user)

Command to run application

/bin/elasticsearch_exporter  - --web.telemetry-path=/_prometheus/metrics

In your deployment it should be something like this

```yaml
        env:
          - name: ES_HOST
            value: my-es-host
          - name: ES_PORT
            value: "9200"
          - name: ES_USER
            value: "elastic"
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret-elastic-user
                key: elastic
          - name: ES_ALL
            value: "true"
          - name: ES_CLUSTER_SETTINGS
            value: "true"
          - name: ES_INDICES
            value: "true"
          - name: ES_INDICES_SETTINGS
            value: "true"
          - name: ES_SHARDS
            value: "true"
          - name: ES_SSL_SKIP_VERIFY
            value: "true"
          - name: ES_URI
            value: "https://$(ES_USER):$(ES_PASSWORD)@$(ES_HOST):$(ES_PORT)"

        command:
        - /bin/elasticsearch_exporter
        - --web.telemetry-path=/_prometheus/metrics
```
