### ISSUE TITLE
Missing Metrics

### ISSUE THREAD

**Issue by Nalum** [justwatchcom/elasticsearch_exporter#92]
I've set this up with the following kubernetes container spec:

```yaml
      - name: elasticsearch-exporter
        image: justwatch/elasticsearch_exporter:1.0.1
        args:
        - --es.uri=http://localhost:9200
        - --es.all=true
        ports:
        - containerPort: 9108
          name: es-exp
```
Should I be doing anything else to get all the metrics?
The metrics I'm seeing in prometheus don't match with the metrics listed in the readme.

```
elasticsearch_cluster_health_json_parse_failures
elasticsearch_cluster_health_total_scrapes
elasticsearch_cluster_health_up
elasticsearch_node_health_json_parse_failures
elasticsearch_node_health_total_scrapes
elasticsearch_node_health_up
```
I'm using elasticsearch version 2.4.1
