### ISSUE TITLE
Update dashboard

### ISSUE THREAD

**Issue by esseti** [justwatchcom/elasticsearch_exporter#95]
Hi,
i'm trying to use this dashboard https://github.com/justwatchcom/elasticsearch_exporter/blob/master/examples/grafana/dashboard.json but it seems not working anymore.

first, if I've the node_exporter installed on all the nodes of the cluster it sums the nodes. I've 2 nodes and the `nodes` displayed are instead 4 since it does a sum and both nodes report 2 for that cluster.

Memory / CPU and other are not showing any data, I think (i'm not an expert) that the exported metrics have changed name.

Does anyone has a dashboard to suggest? i've seen that there are several others in grafana, but I can't get my head around to find something that show cluster + instance usage.

**Comment by zwopir** [comment]
Hi,
sorry for the late reply. The dashboard relies on a relabeling config that adds a label "cluster" to the elasticsearch_exporter metrics (described in https://github.com/justwatchcom/elasticsearch_exporter#alerts--recording-rules).
If you add such a label, the dashboard should work.

**Comment by zwopir** [comment]
it's not the elasticsearch_exporter that needs the label `cluster` added, but the `node_exporter`(s) that a running on the ES nodes. The elasticsearch_exporter itself gets the `cluster` label from the ES API.

So if the `__meta_ec_tag_Name` matches the cluster label value you get from the elasticsearch_exporter, the dashboard should work. Otherwise you need so set the value, either manually in the job definition via `labels` (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config) or via rewriting from some aws ec labels.

**Comment by mtanatwine** [comment]
Ah nice, thanks for the tip. If you want to include a section in the README for AWS users, and for anyone else who may look for this in the future, this is what worked for us:

```
  - job_name: ec2
    ec2_sd_configs:
      - region: eu-west-1
        access_key: xxx
        secret_key: xxx
        profile: xxx
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [instance]
        regex: (.*elasticsearch.*)
        target_label: cluster
        replacement: elasticsearch
```

Our instances contain the word `elasticsearch`, so the regex may need to change if yours aren't set up the same way.
